
import Sidebar from "@/components/SideBar"
import "./globals.css"
import { Inter } from "next/font/google"
import { Toaster } from "react-hot-toast"
import { LayoutProvider } from "@/components/LayoutProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  className={inter.className} suppressHydrationWarning={true}>

      <LayoutProvider>
          {children}
        <Toaster position="bottom-center"/>
      </LayoutProvider>
      </body>
    </html>
  )
}
